# Generated by Django 5.2.1 on 2025-05-11 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_number',
            field=models.CharField(default='0000000000000000', max_length=16, unique=True),
        ),
        migrations.AddField(
            model_name='card',
            name='expiry_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
